// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

char findTheDifference(char * s, char * t){
    int sum = 0;
    while (*s != 0) {
        sum ^= *s;
        s++;
    }
    while (*t != 0) {
        sum ^= *t;
        t++;
    }
    return sum;
}